---
- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Create Docker daemon configuration directory
  file:
    path: /etc/docker
    state: directory

- name: Create Docker daemon configuration
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        },
        "storage-driver": "overlay2"
      }
  notify: restart docker
